server:
  type: default
  # Never change the following param!
  rootPath: /api
  minThreads:  12
  maxThreads: 48
  maxQueuedRequests: 2048
  idleThreadTimeout: 10 seconds

mongoUri: "mongodb://${MONGO_HOST:-localhost}/${MONGO-DB:-reports}?connectTimeoutMS=5000&socketTimeoutMS=90000&w=majority&journal=true&wtimeoutMS=60000"

logging:
  level: INFO

auth:
  secret: fshfhhfhfeoeofeoffzjzjfzjhfhfshhsffpzpzofofeoo
  expiry: 1d

userRepository:
  type: static
  users:
    - name: pgentile
      password: password
      displayName: Pierre Gentile

# LDAP config for an user repository
# userRepository:
#   type: ldap
#   url: ldap://192.168.99.100:389
#   userDn: "cn=admin,dc=example,dc=org"
#   base: "dc=example,dc=org"
#   password: password
#
#   attributeMapping:
#     name: cn
#     displayName: dn
